spring:
  application:
    name: librayapi
  datasource:
    url: jdbc:postgresql://localhost:5444/library
    username: fabada
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
